SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600

DISPLAY_DELAY = 0.1
BUFFER = 20

TURTLE_STARTING_X = 0
TURTLE_STARTING_Y = -int(SCREEN_HEIGHT/2 - BUFFER)
TURTLE_STEP = 10
TURTLE_FINISH = int(SCREEN_HEIGHT/2 -BUFFER)


COLORS = ["red", "orange", "yellow", "green", "blue", "purple"]
STARTING_MOVE_DISTANCE = 5
MOVE_INCREMENT = 5

FONT = ("Courier", 30, "normal")